### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by AvalancheYT** [AlexFreedomRemake/AlexFreedomModBETA#6]
Hello @AlexFreedomMod and @Superior-tL,
I have found that you are using my plugin with any given credits.
Please remove the following ones:
- ```LICENSE.md```

Fail to do so will result in DMCA.
Thanks in advance,
Nathan Curran (AvalancheYT/_JustYellow)

**Comment by Superior-tL** [comment]
Wait what is a DMCA?

**Comment by AvalancheYT** [comment]
DMCA is where the projects get taken down.

**Comment by AlexFreedomMod** [comment]
Done

**Comment by Superior-tL** [comment]
@AlexFreedomMod

**Comment by Superior-tL** [comment]
Can you pay for AlexFreedom?

**Comment by AlexFreedomMod** [comment]
Can't.. .
